Dataset deposit steps
okp4/dataset-deposit-web pull request #55
Opened 2022-09-13 08:38 UTC by JoeyDjr

This PR implements the Dataset deposit by adding the following steps : 

- Data Space selection step
<img width="803" alt="image" src="https://user-images.githubusercontent.com/107192362/189854363-dba24cbf-8f81-4e96-8fe0-fc496260ef5a.png">

- Upload step
<img width="811" alt="image" src="https://user-images.githubusercontent.com/107192362/189853571-61465c0d-7e3d-4180-a032-5368d2c6d200.png">

- Metadata step
<img width="833" alt="image" src="https://user-images.githubusercontent.com/107192362/189853723-db71aa3f-b451-416e-9ec5-9a4b36610b8a.png">

- Summary step
<img width="820" alt="image" src="https://user-images.githubusercontent.com/107192362/189854016-3646957e-e23b-4c86-9d3e-989618c00da2.png">

2022-09-15 08:41 UTC, amimart requested changes
I have only small remarks

2022-09-15 08:41 UTC, amimart commented on src/components/metadataStep/MetadataStep.tsx
> +  datasetTitle: string
For the sake of consistency, and because we know we're talking about datasets :).
```suggestion
  title: string
```

⚠️ There are other similar naming I didn't pointed out

2022-09-15 08:41 UTC, amimart commented on src/components/metadataStep/MetadataStep.tsx
> +    value: 'Agriculture, environment and forestry'
If I understand it well, the `label` isn't displayed, right ? In such case I would have apply a code style on them (e.g. capitalized snake case or kebab case) to avoid confusion and ease usage.

By the way, the categories aren't i18n ?

2022-09-15 09:03 UTC, ccamel commented on src/components/metadataStep/MetadataStep.tsx
> +    value: 'Agriculture, environment and forestry'
I agree with @amimart 
If label is a key, I would expect to have a clear and controlled identifier rather than a free text... This will then facilitate the transition to our [ontology](https://github.com/okp4/ontology) as a data source.

Also, the values should be taken from a language file, that would be better, imho.

2022-09-15 09:03 UTC, lolottetheclash commented on src/components/uploadStep/UploadStep.tsx
> +        <div className="okp4-dataspace-step-description">
`okp4-dataspace-step-description`=> this was the name used for the dataspace step, which belongs to `okp4-dataspace-step-main`: I think you have to adapt it and also on metadata step, summary step.

2022-09-15 09:12 UTC, lolottetheclash commented on src/components/uploadStep/UploadStep.tsx
> +      <FilePicker
I think it could be nice to have the `showClearAll` property here.

2022-09-15 09:30 UTC, lolottetheclash commented on src/components/metadataStep/MetadataStep.tsx
> +    value: 'Agriculture, environment and forestry'
@amimart it is the label that is displayed to the user, and the value is not. This is the label that is retrieved and transmitted once the choice is made.

2022-09-15 09:33 UTC, ErikssonJoakim requested changes
Nice work! Only got some refactoring ideas I think would make the code lighter and more readable 😃

2022-09-15 09:33 UTC, ErikssonJoakim commented on src/components/sumamryStep/SummaryStep.tsx
> +      </Typography>
Small refactoring but it doesn't make sense for me to have two div.

```suggestion
      <div className="okp4-dataspace-step-description">
        <Typography fontSize="small">
          {t('stepper:dataset-deposit:steps:summary:description')}
        </Typography>
      </div>
```

2022-09-15 09:33 UTC, ErikssonJoakim commented on src/components/uploadStep/UploadStep.tsx
> +      </Typography>
Same thing here we could just have the div envelop a span `Typography`.

2022-09-15 09:40 UTC, lolottetheclash commented on src/components/stepper/Stepper.tsx
> +    const mandatoryMetadata =
Maybe you can find a better name because the name of this variable does not reflect that it is a boolean nor that the expected metadata is complete .

2022-09-15 09:43 UTC, lolottetheclash commented on src/components/stepper/Stepper.tsx
> +  const [metadataStepError, setMetadataStepError]: UseState<boolean> = useState<boolean>(false)
I think you should rename `metadataStepError` into a boolean one (also if you can make the same with `dataSpaceStepError`)

2022-09-15 09:48 UTC, lolottetheclash commented on src/components/sumamryStep/SummaryStep.tsx
> +      <div className="okp4-summary-step-field">
I think you can improve the redundancy of this part of code: 
```
<div className="okp4-summary-step-field">
        <Typography fontSize="small" fontWeight="bold">
          {t('stepper:dataset-deposit:steps:summary:form:dataset')}
        </Typography>
        <Typography fontSize="small">{metadata?.datasetTitle}</Typography>
</div>

```
what do you think?
=> This will allow you to delete that too ;)
// eslint-disable-next-line max-lines-per-function

2022-09-16 15:03 UTC, ccamel commented on src/components/metadataStep/MetadataStep.tsx
> +    value: 'Agriculture, environment and forestry'
Ok. So that's the `value` which should be normalized.

2022-09-16 15:10 UTC, ccamel commented on src/components/stepper/Stepper.tsx
> +    const mandatoryMetadata =
@lolottetheclash For sure! 😌 Once again, please read and apply 👉 https://dev.to/michi/tips-on-naming-boolean-variables-cleaner-code-35ig.

2022-09-20 06:01 UTC, amimart approved these changes
LGTM!

2022-10-20 08:56 UTC, JoeyDjr commented
No more up to date. See this PR 👉 https://github.com/okp4/dataset-deposit-web/pull/83 instread.

2022-10-20 08:56 UTC, closed without merging