fix(release): rearrange conventionalcommits preset
okp4/dataset-deposit-web pull request #84
Opened 2022-10-23 21:40 UTC by hleonardtek

Fix the `conventionalcommits` preset of semantic release.

2022-10-24 06:47 UTC, ad2ien approved these changes

2022-10-24 15:14 UTC, amimart requested changes
We need to remove the `releaseRules` to use the preset's ones.

2022-10-24 15:39 UTC, ccamel approved these changes

2022-10-25 07:29 UTC, ccamel approved these changes

2022-10-25 13:35 UTC, amimart approved these changes

2022-10-25 14:21 UTC, merged